### PR TITLE
[WIP] Converting to Typescript library for better communication and clean types

### PR DESCRIPTION
**Pull request by marpme**
# WORK IN PROGRESS - SEARCHING FOR SUPPORT

This should basically update the current structure of the project to be more extendable and easier to use
as you might not now what is coming back from some RPC commands etc.

### OPEN TASK:
* documenting all rpc commands available
* enable all rpc commands and make them work
* Unify further data structures

##### I would really love to see some help from you guys to accomplish this. @justinvforvendetta will be on our side 💯  

Greetings marpme, kyon whatever 💃

### CODE REVIEW

**Comment by marpme** [comment]
Participate if you want to 👍 

#10

**Comment by justinvforvendetta** [comment]
thanks! and hello to the fam on the fb group ;]

**Comment by technotip** [comment]
Is there a node.js typescript library? I'm getting error while trying to require the library in my node application.

**Comment by marpme** [comment]
@technotip that one: https://www.npmjs.com/package/verge-node-typescript but it's kinda missing some functionality.

Those are the supported methods: https://github.com/marpme/verge-node-typescript/blob/master/src/Client.ts#L110-L159

**Comment by technotip** [comment]
@marpme thanks for the response. I tried a lot of these stuffs. But its not working.

If I install using: 

`npm install node-verge`

it doesn't recognize the verge library. When I tried

'npm install verge-node-typescript`

it worked. I mean, it stopped throwing errors. But still its not giving me back any result. No errors too. And the verge.auth(user:any, pass:any) throws error that auth is not a function.

Please we need some documentation. Basic, working documentation will be fine too.

**Comment by technotip** [comment]
There is a command

`sendmany <fromaccount> {address:amount,...} [minconf=1] [comment]`

Isn't it for sending XVG for multiple addresses at once?

**Comment by justinvforvendetta** [comment]
you can install this with git clone, I'll submit it to node pm later today

**Comment by marpme** [comment]
> you can install this with git clone, I'll submit it to node pm later today

Naaah @justinvforvendetta, just leave it as it is. I've created a new typescript one(https://www.npmjs.com/package/verge-node-typescript). No need to overwrite the current node-js lib as it is more feature rich than my one. Many people will complain that things aren't working anymore. :)

**Comment by technotip** [comment]
Guys please let me know what this command does.

`sendmany <fromaccount> {address:amount,...} [minconf=1] [comment]`

I want to send XVG to multiple XVG addresses at once. Is this possible with above command, from wallet console window?

**Comment by marpme** [comment]
yeah that's the command that does it @technotip

**Comment by technotip** [comment]
@marpme Could you please give me an example?

Is this correct:

`sendmany myxvg_address {xvg_address1: 100, xvg_address2: 100, ...}`

What does [minconf=1] [comment] mean?

**Comment by marpme** [comment]
`myxvg_address` might not be your account, you may want to get your accounts by calling `listaccounts` or so

**Comment by technotip** [comment]
I mean, I open my wallet, sync it completely, and then go to the console and then type: 

`sendmany myxvg_address {xvg_address1: 100, xvg_address2: 100, ...}`

I'll use one of my address(that I get from listaccounts command) and replace it with myxvg_address in above command. Will it work?

And please let me know what is  [minconf=1] [comment] ?

**Comment by marpme** [comment]
1. Just try it out with one address, then with more addresses and you will see it.
2. minconf I really don't know / comment is just a comment for the transaction

**Comment by justinvforvendetta** [comment]
minconf = minimum confirmations

**Pull request merged**
